services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - chatting-api
      - chatting-core
    networks:
      - chatting-network

  chatting-api:
    build:
      context: ./chatting-api
    ports:
      - "8090"   # 내부 포트만 개방
    depends_on:
      - db
      - redis
      - chatting-core
    networks:
      - chatting-network

  chatting-core:
    build:
      context: ./chatting-core
    ports:
      - "8091:8091"
    depends_on:
      - redis
    environment:
      - SERVER_NAME=chatting-core
      - SERVER_PORT=8091
    networks:
      - chatting-network

  chatting-core2:
    build:
      context: ./chatting-core
    ports:
      - "8092:8092"
    depends_on:
      - redis
    environment:
      - SERVER_NAME=chatting-core2
      - SERVER_PORT=8092
    networks:
      - chatting-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - chatting-network

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    networks:
      - chatting-network

networks:
  chatting-network:
    driver: bridge
