server:
  port: ${SERVER_PORT:8091} # 환경변수 없으면 기본값 8091

output:
  ansi:
    enabled: always

spring:
  data:
    redis:
      host: redis
      port: 6379

  config:
    import: classpath:common.yml
