server:
  port: 8090

output:
  ansi:
    enabled: always

spring:
  redis:
    host: redis
    port: 6379

  datasource:
    url: jdbc:mysql://db:3306/chatdb
    username: chatuser
    password: chatpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySecretKey
  expiration: 1800000 # 30분 (ms 단위)