server:
  port: 8090

output:
  ansi:
    enabled: always

spring:
  datasource:
    url: jdbc:mysql://db:3306/chatdb
    username: chatuser
    password: chatpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379

  config:
    import: classpath:common.yml
